Fix #14, "requires tensorboard to be installed" RuntimeError
Update pyproject.toml to add `tensorboard` as a dependency of the
`notebooks` target.

The tensorboard package is required for step 10 of
`notebooks/patch_tsmixer_getting_started.ipynb` to run the following
expression:

```
trainer = Trainer(
    model=model,
    args=train_args,
    train_dataset=train_dataset,
    eval_dataset=valid_dataset,
    callbacks=[early_stopping_callback],
)
```

Otherwise the following exception is raised:

```
RuntimeError: TensorBoardCallback requires tensorboard to be installed. Either update your PyTorch version or install tensorboardX.
```

Signed-off-by: Florent Flament <contact@florentflament.com>